[[CURRENCIES]]
code="LUME"
issuer="GDYHMRRP3E4VIRRVTMC2YRHPRBSYK6I7STZRGFNWHPJEBVD3C4QTSDYC"
name="LUMENSIAtoken"
desc="Token utilitas untuk ekosistem LUMENSIA"
image="https://lumensiatoken.netlify.app"

