[[CURRENCIES]]
code="LUME"
issuer="GDDKNNJQPX3OWCRYWFMWWUEOHQMUOSIQ6WL3YNEPLJ6RG7RL6337MRJD"
name="LUMENSIAtoken"
desc="Token utilitas untuk ekosistem LUMENSIA"
image="https://token-lumensia.netlify.app/assets/logo.png"

